name: your_tasks_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  page_transition: ^2.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico/Pacifico-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-Light.ttf
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-Regular.ttf


